# Team name mapping for inconsistent naming in source PDFs
# Maps: detected_name -> canonical_name

team_names:
  hearthkyn-salvager: hearthkyn-salvagers
  raveners: ravener
  angels-of-death: angel-of-death
  hernkyn-yaegirs: hernkyn-yaegir
  farstalker-kinband: farstalker
  wolf-scouts: wolf-scout

# Team metadata including faction and army for v2 output format
# faction: imperium, chaos, xenos
# army: specific army within the faction
team_metadata:
  battleclade:
    canonical_name: "Battleclade"
    faction: "imperium"
    army: "adeptus-mechanicus"
  
  deathwatch:
    canonical_name: "Deathwatch"
    faction: "imperium"
    army: "space-marines"
  
  exaction-squad:
    canonical_name: "Exaction Squad"
    faction: "imperium"
    army: "arbites"
  
  farstalker-kinband:
    alias: farstalker
    canonical_name: "Farstalker Kinband"
    faction: "xenos"
    army: "T'au Empire"
  
  hearthkyn-salvager:
    alias: hearthkyn-salvagers
    canonical_name: "Hearthkyn Salvagers"
    faction: "xenos"
    army: "leagues-of-votann"
  
  wrecka-krew:
    canonical_name: "Wrecka Krew"
    faction: "xenos"
    army: "orks"
  
  angels-of-death:
    alias: angel-of-death
    canonical_name: "Angels of Death"
    faction: "imperium"
    army: "space-marines"
  