# Team configuration for Kill Team datacards
# Defines team metadata including faction, army, and name aliases
# faction: imperium, chaos, xenos
# army: specific army within the faction
# aliases: list of alternative names detected in source PDFs

teams:
  battleclade:
    canonical_name: "Battleclade"
    faction: "imperium"
    army: "adeptus-mechanicus"
    aliases: []
  
  deathwatch:
    canonical_name: "Deathwatch"
    faction: "imperium"
    army: "space-marines"
    aliases: []
  
  exaction-squad:
    canonical_name: "Exaction Squad"
    faction: "imperium"
    army: "arbites"
    aliases: []
  
  farstalker-kinband:
    canonical_name: "Farstalker Kinband"
    faction: "xenos"
    army: "T'au Empire"
    aliases: ["farstalker"]
  
  hearthkyn-salvager:
    canonical_name: "Hearthkyn Salvagers"
    faction: "xenos"
    army: "leagues-of-votann"
    aliases: ["hearthkyn-salvagers"]
  
  wrecka-krew:
    canonical_name: "Wrecka Krew"
    faction: "xenos"
    army: "orks"
    aliases: []
  
  angels-of-death:
    canonical_name: "Angels of Death"
    faction: "imperium"
    army: "space-marines"
    aliases: ["angel-of-death"]
  