# Team name mapping for inconsistent naming in source PDFs
# Maps: detected_name -> canonical_name

team_names:
  hearthkyn-salvager: hearthkyn-salvagers
  raveners: ravener
  angels-of-death: angel-of-death
  hernkyn-yaegirs: hernkyn-yaegir
  farstalker-kinband: farstalker
  wolf-scouts: wolf-scout
  