# Team configuration for Kill Team datacards
# Defines team metadata including faction, army, and name aliases
# faction: imperium, chaos, xenos
# army: specific army within the faction
# aliases: list of alternative names detected in source PDFs

teams:
  battleclade:
    canonical_name: "Battleclade"
    faction: "imperium"
    army: "adeptus-mechanicus"
    aliases: []
  
  deathwatch:
    canonical_name: "Deathwatch"
    faction: "imperium"
    army: "space-marines"
    aliases: []
  
  exaction-squad:
    canonical_name: "Exaction Squad"
    faction: "imperium"
    army: "arbites"
    aliases: []
  
  farstalker-kinband:
    canonical_name: "Farstalker Kinband"
    faction: "xenos"
    army: "T'au Empire"
    aliases: ["farstalker"]
  
  hearthkyn-salvagers:
    canonical_name: "Hearthkyn Salvagers"
    faction: "xenos"
    army: "leagues-of-votann"
    aliases: ["hearthkyn-salvager"]
  
  wrecka-krew:
    canonical_name: "Wrecka Krew"
    faction: "xenos"
    army: "orks"
    aliases: []
    
  wolf-scouts:
    canonical_name: "Wolf Scouts"
    faction: "imperium"
    army: "space-marines"
    aliases: [wolf-scout]
  
  angels-of-death:
    canonical_name: "Angels of Death"
    faction: "imperium"
    army: "space-marines"
    aliases: ["angel-of-death"]
  
  blades-of-khaine:
    canonical_name: "Blades of Khaine"
    faction: "xenos"
    army: "aeldari"
    aliases: ["blade-of-khaine"]
    
  blooded:
    canonical_name: "Blooded"
    faction: "chaos"
    army: "Renegade Guardsmen"
    aliases: []
    
  brood-brothers:
    canonical_name: "Brood Brothers"
    faction: "xenos"
    army: "tyranids"
    aliases: ["brood-brother"]
    
  canoptek-circle:
    canonical_name: "Canoptek Circle"
    faction: "xenos"
    army: "necrons"
    aliases: []

  death-korps:
    canonical_name: "Death Korps"
    faction: "imperium"
    army: "imperial-guard"
    aliases: ["death-korp"]
  
  chaos-cult:
    canonical_name: "Chaos Cult"
    faction: "chaos"
    army: "chaos-cultists"
    aliases: ["chaos-cultist"]
  
  corsair-voidscarred:
    canonical_name: "Corsair Voidscarred"
    faction: "xenos"
    army: "aeldari"
    aliases: []

  hand-of-the-archon:
    canonical_name: "Hand of the Archon"
    faction: "xenos"
    army: "aeldari"
    aliases: []

  fellgor-ravagers:
    canonical_name: "Fellgor Ravagers"
    faction: "chaos"
    army: "chaos-space-marines"
    aliases: ["fellgor-ravager"]

  elucidian-starstriders:
    canonical_name: "Elucidian Starstriders"
    faction: "imperium"
    army: "agents-of-the-imperium"
    aliases: ["elucidian-starstrider"]

  gellerpox-infected:
    canonical_name: "Gellerpox Infected"
    faction: "chaos"
    army: "plague-zombies"
    aliases: []

  goremongers:
    canonical_name: "Goremongers"
    faction: "chaos"
    army: "demons"
    aliases: ["goremonger"]

  