# Team configuration for Kill Team datacards
# Defines team metadata including faction, army, and name aliases
# faction: imperium, chaos, xenos
# army: specific army within the faction
# aliases: list of alternative names detected in source PDFs

teams:
  angels-of-death:
    canonical_name: "Angels of Death"
    faction: "imperium"
    army: "space-marines"
    aliases: ["angel-of-death"]
  
  battleclade:
    canonical_name: "Battleclade"
    faction: "imperium"
    army: "adeptus-mechanicus"
    aliases: []
  
  blades-of-khaine:
    canonical_name: "Blades of Khaine"
    faction: "xenos"
    army: "aeldari"
    aliases: ["blade-of-khaine"]
    
  blooded:
    canonical_name: "Blooded"
    faction: "chaos"
    army: "Renegade Guardsmen"
    aliases: []
    
  brood-brothers:
    canonical_name: "Brood Brothers"
    faction: "xenos"
    army: "tyranids"
    aliases: ["brood-brother"]
    
  canoptek-circle:
    canonical_name: "Canoptek Circle"
    faction: "xenos"
    army: "necrons"
    aliases: []
  
  chaos-cult:
    canonical_name: "Chaos Cult"
    faction: "chaos"
    army: "chaos-cultists"
    aliases: ["chaos-cultist"]
  
  corsair-voidscarred:
    canonical_name: "Corsair Voidscarred"
    faction: "xenos"
    army: "aeldari"
    aliases: []

  death-korps:
    canonical_name: "Death Korps"
    faction: "imperium"
    army: "imperial-guard"
    aliases: ["death-korp"]
  
  deathwatch:
    canonical_name: "Deathwatch"
    faction: "imperium"
    army: "space-marines"
    aliases: []

  elucidian-starstriders:
    canonical_name: "Elucidian Starstriders"
    faction: "imperium"
    army: "agents-of-the-imperium"
    aliases: ["elucidian-starstrider"]
  
  exaction-squad:
    canonical_name: "Exaction Squad"
    faction: "imperium"
    army: "arbites"
    aliases: []
  
  farstalker-kinband:
    canonical_name: "Farstalker Kinband"
    faction: "xenos"
    army: "T'au Empire"
    aliases: ["farstalker"]

  fellgor-ravagers:
    canonical_name: "Fellgor Ravagers"
    faction: "chaos"
    army: "chaos-space-marines"
    aliases: ["fellgor-ravager"]

  gellerpox-infected:
    canonical_name: "Gellerpox Infected"
    faction: "chaos"
    army: "plague-zombies"
    aliases: []

  goremongers:
    canonical_name: "Goremongers"
    faction: "chaos"
    army: "demons"
    aliases: ["goremonger"]

  hand-of-the-archon:
    canonical_name: "Hand of the Archon"
    faction: "xenos"
    army: "aeldari"
    aliases: []
  
  hearthkyn-salvagers:
    canonical_name: "Hearthkyn Salvagers"
    faction: "xenos"
    army: "leagues-of-votann"
    aliases: ["hearthkyn-salvager"]

  hernkyn-yaegirs:
    canonical_name: "Hernkyn Yaegirs"
    faction: "xenos"
    army: "leagues-of-votann"
    aliases: ["hernkyn-yaegir"]
  
  hierotek-circle:
    canonical_name: "Hierotek Circle"
    faction: "xenos"
    army: "necrons"
    aliases: ["hierotek-circle"]
  
  hunter-clade:
    canonical_name: "Hunter Clade"
    faction: "xenos"
    army: "T'au Empire"
    aliases: ["hunter-clade"]
  
  imperial-navy-breachers:
    canonical_name: "Imperial Navy Breachers"
    faction: "imperium"
    army: "imperial-navy"
    aliases: ["imperial-navy-breacher"]
  
  inquisitorial-agents:
    canonical_name: "Inquisitorial Agents"
    faction: "imperium"
    army: "inquisition"
    aliases: ["inquisitorial-agent"]
  
  kasrkin:
    canonical_name: "Kasrkin"
    faction: "imperium"
    army: "imperial-guard"
    aliases: []
  
  kommandos:
    canonical_name: "Kommandos"
    faction: "xenos"
    army: "orks"
    aliases: ["kommando"]
  
  legionaries:
    canonical_name: "Legionaries"
    faction: "chaos"
    army: "chaos-space-marines"
    aliases: ["legionary"]
  
  mandrakes:
    canonical_name: "Mandrakes"
    faction: "xenos"
    army: "aeldari"
    aliases: ["mandrake"]
  
  nemesis-claw:
    canonical_name: "Nemesis Claw"
    faction: "xenos"
    army: "aeldari"
    aliases: ["nemesis-claw"]
  
  novitiates:
    canonical_name: "Novitiates"
    faction: "imperium"
    army: "adeptus-astrates"
    aliases: ["novitiate"]
  
  pathfinders:
    canonical_name: "Pathfinders"
    faction: "xenos"
    army: "T'au Empire"
    aliases: ["pathfinder"]
  
  phobos-strike-team:
    canonical_name: "Phobos Strike Team"
    faction: "imperium"
    army: "space-marines"
    aliases: ["phobos-strike-team"]
  
  plague-marines:
    canonical_name: "Plague Marines"
    faction: "chaos"
    army: "chaos-space-marines"
    aliases: ["plague-marine"]
  
  ratlings:
    canonical_name: "Ratlings"
    faction: "imperium"
    army: "imperial-guard"
    aliases: ["ratling"]
  
  raveners:
    canonical_name: "Raveners"
    faction: "xenos"
    army: "tyranids"
    aliases: ["ravener"]
  
  sanctifiers:
    canonical_name: "Sanctifiers"
    faction: "imperium"
    army: "adeptus-astrates"
    aliases: ["sanctifier", "sancifier"]
  
  scout-squad:
    canonical_name: "Scout Squad"
    faction: "imperium"
    army: "space-marines"
    aliases: ["scout-squad"]
  
  tempestus-aquilons:
    canonical_name: "Tempestus Aquilons"
    faction: "imperium"
    army: "imperial-guard"
    aliases: ["tempestus-aquilon"]
  
  vespid-stingwings:
    canonical_name: "Vespid Stingwings"
    faction: "xenos"
    army: "aeldari"
    aliases: ["vespid-stingwing"]
  
  void-dancer-troupe:
    canonical_name: "Void Dancer Troupe"
    faction: "xenos"
    army: "aeldari"
    aliases: ["void-dancer-troupe"]
  
  warpcoven:
    canonical_name: "Warpcoven"
    faction: "chaos"
    army: "chaos-demons"
    aliases: ["warpcoven"]
    
  wolf-scouts:
    canonical_name: "Wolf Scouts"
    faction: "imperium"
    army: "space-marines"
    aliases: [wolf-scout]
  
  wrecka-krew:
    canonical_name: "Wrecka Krew"
    faction: "xenos"
    army: "orks"
    aliases: []

  wyrmblade:
    canonical_name: "Wyrmblade"
    faction: "xenos"
    army: "aeldari"
    aliases: ["wyrmblade"]
  
  xv26-stealth-battlesuits:
    canonical_name: "XV26 Stealth Battlesuits"
    faction: "xenos"
    army: "T'au Empire"
    aliases: ["xv26-stealth-battlesuit"]